<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snap.Core\Snap.Core.csproj" />
    <ProjectReference Include="..\Snap.Repository\Snap.Repository.csproj" />
  </ItemGroup>

</Project>
